// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// set_attr
RObject set_attr(RObject object_, RObject attr_);
RcppExport SEXP _rcpp_on_solaris_set_attr(SEXP object_SEXP, SEXP attr_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< RObject >::type object_(object_SEXP);
    Rcpp::traits::input_parameter< RObject >::type attr_(attr_SEXP);
    rcpp_result_gen = Rcpp::wrap(set_attr(object_, attr_));
    return rcpp_result_gen;
END_RCPP
}
// set_attr_list
List set_attr_list(List object_, RObject attr_);
RcppExport SEXP _rcpp_on_solaris_set_attr_list(SEXP object_SEXP, SEXP attr_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type object_(object_SEXP);
    Rcpp::traits::input_parameter< RObject >::type attr_(attr_SEXP);
    rcpp_result_gen = Rcpp::wrap(set_attr_list(object_, attr_));
    return rcpp_result_gen;
END_RCPP
}
// set_attr_s4
S4 set_attr_s4(S4 object_, RObject attr_);
RcppExport SEXP _rcpp_on_solaris_set_attr_s4(SEXP object_SEXP, SEXP attr_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type object_(object_SEXP);
    Rcpp::traits::input_parameter< RObject >::type attr_(attr_SEXP);
    rcpp_result_gen = Rcpp::wrap(set_attr_s4(object_, attr_));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_on_solaris_set_attr", (DL_FUNC) &_rcpp_on_solaris_set_attr, 2},
    {"_rcpp_on_solaris_set_attr_list", (DL_FUNC) &_rcpp_on_solaris_set_attr_list, 2},
    {"_rcpp_on_solaris_set_attr_s4", (DL_FUNC) &_rcpp_on_solaris_set_attr_s4, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_rcpp_on_solaris(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
