# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

qatd_cpp_collocations <- function(texts_, types_, words_ignore_, count_min, sizes_, method, smoothing) {
    .Call('_rcpp_on_solaris_qatd_cpp_collocations', PACKAGE = 'rcpp.on.solaris', texts_, types_, words_ignore_, count_min, sizes_, method, smoothing)
}

qatd_cpp_manhattan <- function(A, margin = 1L) {
    .Call('_rcpp_on_solaris_qatd_cpp_manhattan', PACKAGE = 'rcpp.on.solaris', A, margin)
}

qatd_cpp_manhattan2 <- function(A, B, margin = 1L) {
    .Call('_rcpp_on_solaris_qatd_cpp_manhattan2', PACKAGE = 'rcpp.on.solaris', A, B, margin)
}

qatd_cpp_maximum <- function(A, margin = 1L) {
    .Call('_rcpp_on_solaris_qatd_cpp_maximum', PACKAGE = 'rcpp.on.solaris', A, margin)
}

qatd_cpp_maximum2 <- function(A, B, margin = 1L) {
    .Call('_rcpp_on_solaris_qatd_cpp_maximum2', PACKAGE = 'rcpp.on.solaris', A, B, margin)
}

qatd_cpp_canberra <- function(A, margin = 1L) {
    .Call('_rcpp_on_solaris_qatd_cpp_canberra', PACKAGE = 'rcpp.on.solaris', A, margin)
}

qatd_cpp_canberra2 <- function(A, B, margin = 1L) {
    .Call('_rcpp_on_solaris_qatd_cpp_canberra2', PACKAGE = 'rcpp.on.solaris', A, B, margin)
}

qatd_cpp_minkowski <- function(A, margin = 1L, p = 2) {
    .Call('_rcpp_on_solaris_qatd_cpp_minkowski', PACKAGE = 'rcpp.on.solaris', A, margin, p)
}

qatd_cpp_minkowski2 <- function(A, B, margin = 1L, p = 2) {
    .Call('_rcpp_on_solaris_qatd_cpp_minkowski2', PACKAGE = 'rcpp.on.solaris', A, B, margin, p)
}

qatd_cpp_fcm <- function(texts_, n_types, weights_, boolean, ordered) {
    .Call('_rcpp_on_solaris_qatd_cpp_fcm', PACKAGE = 'rcpp.on.solaris', texts_, n_types, weights_, boolean, ordered)
}

qatd_cpp_kwic <- function(texts_, types_, words_, pats_, window, delim_) {
    .Call('_rcpp_on_solaris_qatd_cpp_kwic', PACKAGE = 'rcpp.on.solaris', texts_, types_, words_, pats_, window, delim_)
}

set_attr <- function(object_, attr_) {
    invisible(.Call('_rcpp_on_solaris_set_attr', PACKAGE = 'rcpp.on.solaris', object_, attr_))
}

set_attr_list <- function(object_, attr_) {
    invisible(.Call('_rcpp_on_solaris_set_attr_list', PACKAGE = 'rcpp.on.solaris', object_, attr_))
}

set_attr_s4 <- function(object_, attr_) {
    invisible(.Call('_rcpp_on_solaris_set_attr_s4', PACKAGE = 'rcpp.on.solaris', object_, attr_))
}

qatd_cpp_tokens_chunk <- function(texts_, types_, size, overlap) {
    .Call('_rcpp_on_solaris_qatd_cpp_tokens_chunk', PACKAGE = 'rcpp.on.solaris', texts_, types_, size, overlap)
}

qatd_cpp_tokens_compound <- function(texts_, compounds_, types_, delim_, join, window_left, window_right) {
    .Call('_rcpp_on_solaris_qatd_cpp_tokens_compound', PACKAGE = 'rcpp.on.solaris', texts_, compounds_, types_, delim_, join, window_left, window_right)
}

qatd_cpp_tokens_lookup <- function(texts_, types_, words_, keys_, overlap, nomatch) {
    .Call('_rcpp_on_solaris_qatd_cpp_tokens_lookup', PACKAGE = 'rcpp.on.solaris', texts_, types_, words_, keys_, overlap, nomatch)
}

qatd_cpp_tokens_ngrams <- function(texts_, types_, delim_, ns_, skips_) {
    .Call('_rcpp_on_solaris_qatd_cpp_tokens_ngrams', PACKAGE = 'rcpp.on.solaris', texts_, types_, delim_, ns_, skips_)
}

qatd_cpp_tokens_recompile <- function(texts_, types_, gap = TRUE, dup = TRUE) {
    .Call('_rcpp_on_solaris_qatd_cpp_tokens_recompile', PACKAGE = 'rcpp.on.solaris', texts_, types_, gap, dup)
}

qatd_cpp_tokens_replace <- function(texts_, types_, patterns_, replacements_) {
    .Call('_rcpp_on_solaris_qatd_cpp_tokens_replace', PACKAGE = 'rcpp.on.solaris', texts_, types_, patterns_, replacements_)
}

qatd_cpp_tokens_segment <- function(texts_, types_, patterns_, remove, position) {
    .Call('_rcpp_on_solaris_qatd_cpp_tokens_segment', PACKAGE = 'rcpp.on.solaris', texts_, types_, patterns_, remove, position)
}

qatd_cpp_tokens_select <- function(texts_, types_, words_, mode, padding, window_left, window_right, pos_from_, pos_to_) {
    .Call('_rcpp_on_solaris_qatd_cpp_tokens_select', PACKAGE = 'rcpp.on.solaris', texts_, types_, words_, mode, padding, window_left, window_right, pos_from_, pos_to_)
}

qatd_cpp_is_grouped_numeric <- function(values_, groups_) {
    .Call('_rcpp_on_solaris_qatd_cpp_is_grouped_numeric', PACKAGE = 'rcpp.on.solaris', values_, groups_)
}

qatd_cpp_is_grouped_character <- function(values_, groups_) {
    .Call('_rcpp_on_solaris_qatd_cpp_is_grouped_character', PACKAGE = 'rcpp.on.solaris', values_, groups_)
}

qatd_cpp_set_load_factor <- function(type, value) {
    invisible(.Call('_rcpp_on_solaris_qatd_cpp_set_load_factor', PACKAGE = 'rcpp.on.solaris', type, value))
}

qatd_cpp_get_load_factor <- function() {
    .Call('_rcpp_on_solaris_qatd_cpp_get_load_factor', PACKAGE = 'rcpp.on.solaris')
}

qatd_cpp_set_meta <- function(object_, meta_) {
    invisible(.Call('_rcpp_on_solaris_qatd_cpp_set_meta', PACKAGE = 'rcpp.on.solaris', object_, meta_))
}

qatd_cpp_tbb_enabled <- function() {
    .Call('_rcpp_on_solaris_qatd_cpp_tbb_enabled', PACKAGE = 'rcpp.on.solaris')
}

qatd_cpp_is_overlap <- function(x1_, y1_, w1_, h1_, boxe_) {
    .Call('_rcpp_on_solaris_qatd_cpp_is_overlap', PACKAGE = 'rcpp.on.solaris', x1_, y1_, w1_, h1_, boxe_)
}

